"""Add usage_json to chat_history

Revision ID: 0d7116d16f09
Revises: 6dccb1b79e30
Create Date: 2026-07-26 02:49:39.182518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7116d16f09'
down_revision: Union[str, None] = '6dccb1b79e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('usage_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'usage_json')
    # ### end Alembic commands ###
