"""add_notebook_id_to_chat_sessions

Revision ID: 12c8cdb81ef8
Revises: 8b794b52708f
Create Date: 2026-07-28 07:10:41.394223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_notebook_id_to_chat_sessions

Revision ID: 12c8cdb81ef8
Revises: 8b794b52708f
Create Date: 2026-07-28 07:10:41.394223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c8cdb81ef8'
down_revision: Union[str, None] = '8b794b52708f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notebook_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_sessions_notebook_id'), ['notebook_id'], unique=False)
        batch_op.create_foreign_key('fk_chat_sessions_notebook_id', 'notebooks', ['notebook_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_sessions_notebook_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_sessions_notebook_id'))
        batch_op.drop_column('notebook_id')
    # ### end Alembic commands ###
