"""Update model_configs for multi-config

Revision ID: 60065e81bb62
Revises: 8197ecc97788
Create Date: 2026-07-20 13:59:17.462065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60065e81bb62'
down_revision: Union[str, None] = '8197ecc97788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_configs', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('model_configs', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_model_configs_user_id'), table_name='model_configs')
    op.create_index(op.f('ix_model_configs_user_id'), 'model_configs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_configs_user_id'), table_name='model_configs')
    op.create_index(op.f('ix_model_configs_user_id'), 'model_configs', ['user_id'], unique=True)
    op.drop_column('model_configs', 'is_active')
    op.drop_column('model_configs', 'name')
    # ### end Alembic commands ###
