"""Add capability_tier to model_configs

Revision ID: 8b794b52708f
Revises: e5b3f92c7a41
Create Date: 2026-07-28 05:38:46.699634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b794b52708f'
down_revision: Union[str, None] = 'e5b3f92c7a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_configs', sa.Column('capability_tier', sa.String(length=50), server_default='tidak_didukung', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_configs', 'capability_tier')
    # ### end Alembic commands ###
