"""add images_json to chat_history

Revision ID: da0b2d7a7d7a
Revises: 0d7116d16f09
Create Date: 2026-07-26 05:46:30.892899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0b2d7a7d7a'
down_revision: Union[str, None] = '0d7116d16f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('images_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'images_json')
    # ### end Alembic commands ###
